services:
    mongodb:
        container_name: mongodb
        image: mongo:latest
        restart: unless-stopped
        ports:
            - 27017:27017
        volumes:
            - ./mongo-data/:/data/db
        networks:
            - internal-networks
    app:
        image: "whatsapp-api-app"
        container_name: whatsapp-api-app
        build:
            context: .
            dockerfile: Dockerfile
            args:
                - PORT=${PORT}
                - uid=1000
        depends_on:
            - mongodb
        restart: unless-stopped
        env_file: .env
        ports:
            - ${PORT}:${PORT}
        environment:
            - TOKEN=${TOKEN}
            - PORT=${PORT}
            - MONGODB_ENABLED=${MONGODB_ENABLED}
            - MONGODB_URL=mongodb://mongodb:27017
            - WEBHOOK_ENABLED=${WEBHOOK_ENABLED}
            - WEBHOOK_URL=${WEBHOOK_URL}
            - WEBHOOK_BASE64=${WEBHOOK_BASE64}
        volumes:
            - ./:/home/node/app
        networks:
            - internal-networks
volumes:
    mongo-data:
networks:
  internal-networks:
    name: "whatsapp-api"
    driver: bridge

